5 minute aggregates
cagov/caldata-mdsa-caltrans-pems pull request #196
Opened 2024-05-01 23:03 UTC by mmmiah

Included weighted speed and imputed speed!

2024-05-02 17:03 UTC, kengodleskidot requested changes
Nice job Mintu and we are close! We will want to meet with ODI and get direction from them on the best way to implement my comments and complete these models.

2024-05-02 18:57 UTC, mmmiah commented on transform/models/intermediate/performance/int_performance__five_min_perform_metrics.sql
> +        volume_sum * length / nullifzero(weighted_speed) as observed_vht,
implemented! Thanks!

2024-05-02 18:57 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__five_minute_station_agg.sql
> +        coalesce(weighted_speed, (volume_sum * 22) / nullifzero(average_occupancy) * (1 / 5280) * 12) as imputed_speed
implemented! Thanks!

2024-05-02 18:57 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__five_minute_station_agg.sql
> +        sum(volume) as volume_sum,
implemented! Thanks!

2024-05-06 19:58 UTC, kengodleskidot commented
Please add @britt-allen to this review as well.

2024-05-08 19:51 UTC, mmmiah commented on transform/models/intermediate/performance/int_performance__five_min_perform_metrics.sql
> +            as is_speed_imputed
Alright! Changed from 'speed_imputed' to 'speed_calculated'

2024-05-08 19:59 UTC, mmmiah commented on transform/models/intermediate/performance/int_performance__five_min_perform_metrics.sql
> +        coalesce(speed_five_mins != speed_weighted or speed_five_mins is not null and speed_weighted is null, false)
As we were not able the calculate the speed for all the station where we do not know the volume and occupancy, therefore, there will be still null in 'speed_five_mins after calculation. Now if we use "coalesce(speed_weighted is null, false)"., it will also return null rows as true which we still did not imputed due to lack of volume and occupancy info. I just tested your quarry and it seems that null rows also shows true. To avoid this I think that the current command reflects the exact status of TRUE and FALSE. I will show you the test in meeting! and looking forward to .yml techniques.

2024-05-08 23:15 UTC, kengodleskidot approved these changes
Nice job @mmmiah!

2024-05-08 23:16 UTC, merged

2024-05-15 21:00 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__five_minute_station_agg.sql
> +        sum(volume) as volume_sum,
>  Let's go over the variable naming convention with ODI so we can be consistent in our models. I am thinking we could include the aggregation level to the end instead of the actual aggregation type. For example, the 5-minute volume would be volume_five_min, for the hour aggregation we could use volume_hour, etc.

@kengodleskidot I love this idea. In general our team hasn't been very prescriptive about naming conventions, since it's hard to come up with something that works for every project, but having something like this can be hugely helpful for legibility.