Spatial and temporal aggregation
cagov/caldata-mdsa-caltrans-pems pull request #215
Opened 2024-05-22 03:32 UTC by mmmiah

This pull aggregated speed, volume, occupancy, vmt, vht,  q and delay for different temporal resolution (hourly, daily, weekly and monthly). While aforementioned temporal aggregation again varies by station, lane, city, county, district and type of the roads. The details of this PR background is described in issue #205. Please read detail over there.

2024-05-28 20:30 UTC, kengodleskidot requested changes
Let me know if you have any questions.

2024-05-28 20:30 UTC, kengodleskidot commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_hourly_agg.sql
> +        extract(hour from sample_timestamp) as sample_hour
This extract function returns a numeric value and I believe we will want a timestamp related value instead. Please look into the dateadd/floor function in the five_minute_station_agg model:
        dateadd(
            'minute',
            floor(minute(sample_timestamp) / 5) * 5,
            trunc(sample_timestamp, 'hour')
        ) as sample_timestamp_trunc

2024-05-28 20:30 UTC, kengodleskidot commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +        daily_vmt / nullifzero(daily_vht) as q_value,
Update to daily_q_value for naming convention consistency. This applies to all models where we are aggregating to various temporal timeframes (monthy_q_value, weekly_q_value, etc.). Similar for TTI.

2024-05-28 20:30 UTC, kengodleskidot commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_weekly_agg.sql
> +        sum(volume_sum * daily_speed) / nullifzero(sum(volume_sum)) as weekly_speed,
Do we need speed aggregated to the weekly, monthly, yearly level? We may want to stop aggregating speed at the daily level.

2024-05-29 22:30 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_hourly_agg.sql
> +        extract(hour from sample_timestamp) as sample_hour
Alright, created time stamp as sample_hour which includes date and hour, for daily, just used the sample date. For week, I created year, number of week and also starting and ending date of week to provide clear temporal coverage, for monthly aggregation just reported month and year separately

2024-05-29 22:32 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +        daily_vmt / nullifzero(daily_vht) as q_value,
Done!

2024-05-29 22:33 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_weekly_agg.sql
> +        sum(volume_sum * daily_speed) / nullifzero(sum(volume_sum)) as weekly_speed,
Agreed! We will report only hourly and daily speed, not weekly and monthly

2024-06-04 04:50 UTC, kengodleskidot reviewed
Mostly minor comments with the need for additional model work to calculate delay in accordance with #201 and discussion around how we want to handle the Productivity calculation at the hourly level.

2024-06-04 04:50 UTC, kengodleskidot commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
> +                as delay_{{ value }}_mph
@mmmiah when it comes to calculating delay across all lanes at a station, the flow weighted speed across all lanes needs to be used in calculating the delay metric and not just summing the per lane delay at a station. Issue #201 describes the delay calculation at the station level in more detail. This variation of the delay calculation could be added to the existing five_min_perform_metrics model but it can also be done as it's own separate model.

2024-06-04 04:50 UTC, kengodleskidot commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_weekly_agg.sql
> +        dateadd(day, 6, date_trunc('week', sample_date)) as sample_week_end_date
I recommend referencing the following link in your code as a comment which contains the details of how Snowflake handles the week functionality: https://docs.snowflake.com/en/sql-reference/functions-date-time#label-calendar-weeks-weekdays.

2024-06-04 04:50 UTC, kengodleskidot commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_weekly_agg.sql
> +        dateadd(day, 6, date_trunc('week', sample_date)) as sample_week_end_date
I recommend referencing the following link in your code as a comment which contains the details of how Snowflake handles the week functionality: https://docs.snowflake.com/en/sql-reference/functions-date-time#label-calendar-weeks-weekdays.

2024-06-04 18:30 UTC, ian-r-rose reviewed
Thanks @mmmiah . Two high-level requests:

1. Our thinking on this is still evolving, but I think we might save ourselves some work down the line by avoiding joining with the metadata here until we decide how to handle it in #214. Right now, there is a lot of inconsistency in what we are doing, and it is an expensive join in many circumstances. By joining at the hourly stage, it's also forcing you into some odd contortions with group by keys (in a lot of cases, `any_value` might work better). But at the time being, I think there is a lot of value in keeping these aggregations as simple as we possibly can, and doing metadata joins in other more models. I'm open to push-back here, but the number of group by keys started to make me feel like there is room for simplification. Basically all of the temporal models should just need to be grouped by a station id, a lane, and a timestamp.
2. Can you add YAML metadata for your new models?

2024-06-04 18:30 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_hourly_agg.sql
> +    from {{ ref('int_clearinghouse__most_recent_station_meta') }} as station_meta_data
Agree with @kengodleskidot here

2024-06-04 18:30 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
I think this might be the same as @kengodleskidot's comment below, but should these aggregates be flow-weighted? As is, they are naive sums and averages across lanes.

2024-06-04 18:30 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_weekly_agg.sql
> +        dateadd(day, 6, date_trunc('week', sample_date)) as sample_week_end_date
I agree that it would be helpful to reference the docs here. Are we okay with the default of 0=Monday for week start?

Do we need to include the end date at all here? It might be simpler to remove this column and just have users compute it if they need it. Right now, I could see us running into trouble with adding "6" to the week rather than "7". I more ususally see a full seven days for weeks, and logic is done exclusive of the end date.

2024-06-04 18:30 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_monthly_agg.sql
> +        type,
I think we might want to take a step back here and *not* include these metadata just yet until we decide how to handle it in #214. As is, these metadata are making this a bit more difficult to maintain, and adding all sorts of unneeded group by keys.

Once we are at the daily and monthly level, I think it would be more tractable to join with metadata on demand in a different downstream model. But I think there's a lot of value in keeping the larger incremental models *as simple as possible*, with as few joins as possible, to avoid needing to do frequent re-computing of things as our thinking evolves.

2024-06-05 03:10 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_weekly_agg.sql
> +        type,
done!

2024-06-05 03:10 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_daily_agg.sql
> +        type,
done!

2024-06-05 03:10 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
> +        station_meta_data.type
done!

2024-06-05 03:11 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
> +                as delay_{{ value }}_mph
Implemented_weighted_delay! Please have a review on formula! Thanks!

2024-06-05 03:12 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_weekly_agg.sql
> +        dateadd(day, 6, date_trunc('week', sample_date)) as sample_week_end_date
Included reference, and also dropped week end date! I think that Monday=0 and Sunday =6 numbering is fine as you included the reference for the user

2024-06-05 03:12 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_weekly_agg.sql
> +        dateadd(day, 6, date_trunc('week', sample_date)) as sample_week_end_date
done!

2024-06-05 03:12 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_hourly_agg.sql
> +        station_meta_data.type
done!

2024-06-05 03:15 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +        cast(sample_hour as date) as sample_date
Did not really keep date with hourly_timestamp as hourly_timestamp had already the date and hour. However, as we are concern about the computation. I have brought the sample_date back from five-minute version! Thank you for helping efficient coding!

2024-06-05 03:16 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
Implemented flow weighted delay in new PR!

2024-06-05 03:17 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_daily_agg.sql
> +            sum(lost_productivity_{{ value }}_mph)
Sure, lets have a discussion tomorrow on this! Thanks for bring it on the table!

2024-06-05 03:18 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_hourly_agg.sql
> +    from {{ ref('int_clearinghouse__most_recent_station_meta') }} as station_meta_data
Sure, lets have a discussion tomorrow on this! then I will work on further modification of these meta data

2024-06-07 20:30 UTC, britt-allen commented
Hey Mintu, is this ready for review now or is there work still being done in the background?

2024-06-07 20:40 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_weekly_agg.sql
> +        type,
what column represents route?

2024-06-07 21:17 UTC, mmmiah commented
@britt-allen , yes, this ready for the review and probably need to merge with main if there is no additional comments. Freeway is the route in this model

2024-06-07 22:44 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +        type,
the status of this is unclear, if it's resolved please resolve it

2024-06-07 22:44 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_monthly_agg.sql
> +        type,
the status of this is unclear, if it's resolved please resolve it

2024-06-07 22:44 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_weekly_agg.sql
> +        type,
the status of this is unclear, if it's resolved please resolve it

2024-06-07 22:44 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_daily_agg.sql
> +            sum(lost_productivity_{{ value }}_mph)
the status of this is unclear, if it's resolved please resolve it

2024-06-07 22:53 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_weekly_agg.sql
> +        type,
This is already done!

2024-06-07 22:55 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_monthly_agg.sql
> +        type,
meta data has added in from daily level to keep the model less expensive while hourly model did not include meta data to avoid expensive joining and aggregation. route and direction was added in daily, weekly and monthly model but not in hourly model as five mins agg do not have this info.

2024-06-07 22:56 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_weekly_agg.sql
> +        type,
Freeway

2024-06-07 22:56 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +        type,
it is already done!

2024-06-07 22:57 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_monthly_agg.sql
> +        type,
it is already done!

2024-06-07 23:01 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__temporal_daily_agg.sql
> +            sum(lost_productivity_{{ value }}_mph)
We need to wait for this to have meeting with traffic people. In the mean time, we are doing some research to see what makes sense. Do we really sum up lost productivity to get hourly, weekly and monthly or will we use five mins formula? We will do both approach test and decide!

2024-06-10 20:13 UTC, mmmiah commented
This ready for final look and merge with main!

2024-06-10 20:28 UTC, ian-r-rose reviewed
Thanks @mmmiah, this looks great! I have a couple of *very* minor comments, but I think this could go in today!

2024-06-10 20:28 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/_clearinghouse.yml
> +        description: end date of last service from station
I don't think this is correct. It's the date of the metadata file, but that doesn't necessarily have anything to do with the activation or service dates of the station. Some metadata files are updated daily, but that doesn't indicate anything about servicing, really, it just indicates the IT strategy of how the metadata is transmitted

2024-06-10 20:28 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_monthly_agg.sql
> +        month(sample_date) as sample_month
Is there a reason you've split these into two different columns rather than just using `date_trunc(month, sample_date)`? I could see it going both ways, but all of the other levels of temporal aggregation use the truncated version, with the understanding that it refers to the whole week, day, hour, etc.

Or if we do want these columns, could we also include a `sample_timestamp_trunc` one so that applications which use timestamps could also use that without having to reconstruct it?

2024-06-10 20:28 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
Is it possible to implement this model as a further aggregation on top of `int_clearinghouse__station_hourly_agg`? Basically, taking that model and doing another group by/agg without `lane`? That would be a bit less work to aggregate (this one might not need to be incremental), and could help keep the two models (lane level and station level) better in sync if the methodology changes.

2024-06-10 20:28 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +    from {{ ref('int_clearninghouse__station_temporal_hourly_agg') }}
Same question here as with the hourly one: is it possible/desirable to implement this model on top of the `int_clearinghouse__temporal_daily_agg`?

2024-06-10 20:28 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
> +        length,
Not a problem with this PR, but I noticed that a lot of the stations have `null` for the `length`. It seems that it's missing for a lot of the station metadata. Does that create significant problems for many of the downstream metrics?

2024-06-10 20:46 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_monthly_agg.sql
> +        month(sample_date) as sample_month
As this is the monthly aggregation you can only store 'year-month' not really any day information. My understanding is that 'date_trunc(month, sample_date)' this will return year-month-first day of the month' which will confuse as it is not only for first day of the month aggregation, it is actually for whole month. That's makes me to generate two columns , one for year and another for month.

2024-06-10 20:48 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_monthly_agg.sql
> +        month(sample_date) as sample_month
But doesn't the timestamp for the weekly aggregation have the same feature? With that, you solved it by just calling it the start date, which you could do for month as well

2024-06-10 21:33 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_monthly_agg.sql
> +        month(sample_date) as sample_month
I see your logic. Just updated it as 'date_trunc(month, sample_date) as sample_month'. this is now reporting just first date of each particular month and user can extract the year and month from this sample_month.

2024-06-10 22:06 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
Was using 'int_clearinghouse__temporal_hourly_agg' to get station level aggregation ''int_clearinghouse__station_hourly_agg'  encountered error as 'HOURLY_LANE_LEVEL_AGG.HOURLY_VMT' in select clause is neither an aggregate nor in the group by clause. may we do not have calculated VMT for all lanes and having single lane VMT raise the error

2024-06-10 22:12 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_temporal_daily_agg.sql
> +    from {{ ref('int_clearninghouse__station_temporal_hourly_agg') }}
as the Hourly level raise the error, I believe that daily level will also raise the same error. We have two cases, case 1: multiple data points for aggregation; case 2: single data points need to be aggregated (this will raise error)

2024-06-10 22:20 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
> +        length,
only vht and Delay depends on length directly which is obviously impacted by null length. Again we are using vht for q value and consequently tti. I will say yes, delay, vht, q value and tti are impacted with this null length. We need to have a discussion how to fill this gap.

2024-06-10 22:40 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/_clearinghouse.yml
> +        description: end date of last service from station
updated this as-         
      - name: STATION_VALID_FROM
        description: Starting date of this aggregation
      - name: STATION_VALID_TO
        description: end date of this aggregation

2024-06-10 22:40 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearninghouse__station_temporal_hourly_agg.sql
Okay, fair enough. I think it may be possible but I think we can leave it for a follow-up investigation.

2024-06-10 22:41 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/_clearinghouse.yml
> +        description: end date of last service from station
Any thoughts here @mmmiah?

2024-06-10 22:54 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/_clearinghouse.yml
> +        description: end date of last service from station
I am not sure the right term here. May be something like this-
- name: STATION_VALID_FROM
description: Starting date of reported data from the station
- name: STATION_VALID_TO
description: end date of reported data from the station
@kengodleskidot may have better terminology

2024-06-10 23:03 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/_clearinghouse.yml
> +        description: end date of last service from station
The description given in the base model should still be correct: https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/8f296641e10c5740f211791265810da608a8f867/transform/models/intermediate/clearinghouse/_clearinghouse.yml#L42-L51

To be honest, I'm not sure that we need to keep these columns in the models: they are needed for the join with the metadata, but once it is joined, I don't think they are needed anywhere else, and aren't really important for the content of the models (like "length" is).

What if we just delete these columns all-together?

2024-06-10 23:25 UTC, mmmiah commented on transform/models/intermediate/clearinghouse/_clearinghouse.yml
> +        description: end date of last service from station
No, Agree, we need them just for joining, not really other purposes. cleaned the code by dropping those! Thanks!

2024-06-10 23:38 UTC, ian-r-rose approved these changes
I'm happy with this when you are @mmmiah, thanks! Feel free to merge when ready

2024-06-11 00:02 UTC, mmmiah commented
@kengodleskidot @britt-allen , can anyone have a final look and have merged this tomorrow? Thank you!

2024-06-11 16:46 UTC, merged

2024-06-13 16:49 UTC, mmmiah commented
This is completed and closed