Bottlenecks
cagov/caldata-mdsa-caltrans-pems pull request #219
Opened 2024-05-30 21:07 UTC by britt-allen

This will close issue #186

2024-05-30 22:32 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__calculate_distance.sql
> +    from {{ ref ("stg_clearinghouse__station_meta") }}
You'll want to select from the intermediate model, which adds the `_valid_from` and `_valid_to` fields.

2024-05-30 22:32 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__calculate_distance.sql
> +            as distance_delta
I don't understand why we need to split this into two window functions. They are partitioned by the same thing, so I would think you could just sort by absolute postmile in the first place

2024-05-30 22:32 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__calculate_distance.sql
> +        to_decimal(absolute_postmile, 6, 3) as absolute_postmile,
Why do you need to convert to decimal?

2024-05-30 22:50 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__calculate_distance.sql
> +        to_decimal(absolute_postmile, 6, 3) as absolute_postmile,
I dunno

2024-06-06 15:13 UTC, kengodleskidot reviewed
Great progress @britt-allen! Let me know if you want to go over anything regarding this model.

2024-06-06 15:13 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        and to_time(sample_timestamp) <= {{ var("day_end") }}
You can remove the timeframe criteria (day_start and day_end) from the where statement since we would want to identify bottlenecks that occur anytime during the day.

2024-06-06 15:13 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        {% endif %}
Since this block only applies to an incremental model you may want to update this to an incremental model. It is currently a table as defined on line 1.

2024-06-06 15:13 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            over (partition by sample_timestamp, freeway, direction, type, lane order by absolute_postmile asc)
Since bottlenecks are analyzed across all lanes you will likely want to remove the lane as part of this partition.

2024-06-06 15:13 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +select * from drop_persists_check
Great progress so far @britt-allen! We will want to incorporate the speed drop persists for at least 5 out of any 7 contiguous 5-minute data points criteria and ultimately, we want the duration, extent and delay associated with the bottlenecks. I have added the technical paper to #186 for reference.

2024-06-07 20:45 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        delay_60_mph,
Once Mintu's PR is merged I'll swap values

2024-06-07 21:10 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        {% endif %}
I actually misspoke. I want to materialized the performance metric model incrementally, but not the bottleneck model

2024-06-07 21:16 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        {% endif %}
I actually want to materialize this incrementally

2024-06-26 20:51 UTC, britt-allen commented
@kengodleskidot we noticed a few instances where speed was 0 and triggered a bottleneck_start because the other conditions were true as well. do we want to filter out instances of speed being zero for flagging the start of a bottleneck?

2024-06-26 20:54 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +select * from drop_persists_check
Can you clarify if for this PR we just want to focus on getting bottleneck start and once tackled, I can open a new pr for bottleneck continues and ends respectively? Ian and I seemed to remember different things about the intent for this PR based on our oral disscusion last week.

2024-06-27 16:40 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        we are planning to have more discussion on how to define the continuation of a bottleneck **/
We do still want to do this in this PR. The part that we are deferring until later is figuring out the extent of congestion, not the 5-out-of-7 check

2024-06-27 16:41 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    snowflake_warehouse = get_snowflake_refresh_warehouse(small="XL")
Let's do small = "XS" and large = "XL"

2024-06-27 17:36 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_ne >= 40
Do we need this check? Based on my read of the criteria, we don't care about the previous speed, just the speed at the current station. We do, however, care about the speed delta.

2024-06-27 17:36 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_sw >= 40
Same question, I don't think this check is described in the criteria.

2024-06-27 17:36 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
This model needs some YAML

2024-06-27 17:36 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
This model also needs YAML

2024-06-27 17:36 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        -- end as bottleneck_cont
Let's not keep around commented-out code

2024-06-27 17:36 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
No need to order these models, it conflicts with the `cluster_by` directive above and causes unnecessary work

2024-06-27 18:02 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    unique_key=["id", "sample_timestamp"],
There may be some performance improvements if we also include `sample_date` in the unique keys, since that's the clustering key for the table

2024-06-27 18:53 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    unique_key=["id", "sample_timestamp"],
Makes sense!

2024-06-27 18:54 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
Can you explain conceptually how it conflicts? I just want to deepen my understanding of what's happening. I'll remove though!

2024-06-27 18:54 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
Does it now? 😮‍💨

2024-06-27 18:56 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
😔

2024-06-27 18:59 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_ne >= 40
Without this check we cannot distinguish if we are in the middle of a bottleneck or the start of one. This was something I discussed with @kengodleskidot and he seemed to agree. I believe that part of building this model is challenging the existing criteria and updating it logically if we see an opportunity to improve. Other than it not being in the existing criteria is there a logical reason why you would not include this to make the bottleneck_start criteria more sound?

2024-06-27 19:00 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    snowflake_warehouse = get_snowflake_refresh_warehouse(small="XL")
Okay! This was copied and pasted code btw so this change likely needs to be corrected elsewhere too.

2024-06-27 19:02 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        we are planning to have more discussion on how to define the continuation of a bottleneck **/
Doesn't a bottleneck lasting for 35 minutes or more constitute it's extent? If not, can you point me to the block of text you are reading that makes you think otherwise?

2024-06-27 19:12 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
When we cluster by `sample_date`, that sorts by that key. It's not a huge conflict, since sorting by `sample_timestamp` and `sample_date` are basically consistent, but it leaves us open to extra work.

Order by is most useful for final queries, but it is not super useful for intermediate results with Snowflake. Some more guidance is [here](https://docs.snowflake.com/en/sql-reference/sql/create-table#usage-notes)

2024-06-27 19:16 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_ne >= 40
Doesn't the `speed_delta` tell us whether we are in the start of a bottleneck or the middle of one? I don't really see what the `speed_prev` check adds on top of the `speed_delta` check. No objection to refining the criteria if we see room for improvement, to be clear.

2024-06-27 19:17 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
Thank you Ian!

2024-06-27 19:18 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        we are planning to have more discussion on how to define the continuation of a bottleneck **/
I should be clearer: we've talked about both the spatial and the temporal extent of the bottlenecks. My understanding was we are deferring any treatment of the spatial extent of the bottleneck. The temporal extent, however(5 out of 7 measurements) is still useful for determining whether a bottleneck occurs for a sustained amount of time.

2024-06-27 19:19 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +        we are planning to have more discussion on how to define the continuation of a bottleneck **/
Understood and agree! Thanks for the clarity.

2024-06-27 19:21 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    snowflake_warehouse = get_snowflake_refresh_warehouse(small="XL")
Yeah, we need to do a pass through the warehouse configs to clean them up. I'd like to take a closer look once some of the performance-related stuff is stable.

2024-06-27 19:23 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
One of the things that's not obvious about incremental models, is that when you add a clustering key, dbt itself adds an `order by` in the final sql (you can see that executing ins Snowflake when you run an incremental model). So it's possible to accidentally sort and then re-sort a table.

Probably not a big deal here since `sample_timestamp` is already consistent with `sample_date`, but in general it's good practice to avoid `order by` here unless we have a strong reason to do it.

2024-06-27 19:26 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
This is something that @JamesSLogan has pointed out in the past, and may have some additional insights about ordering

2024-06-27 20:05 UTC, JamesSLogan commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +    order by sample_timestamp asc, freeway asc, direction asc, type asc, absolute_postmile asc
No additional insights from me!

2024-06-27 20:25 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    snowflake_warehouse = get_snowflake_refresh_warehouse(small="XL")
Should I change this on the bottlenecks model too or only on this one? @ian-r-rose

2024-06-27 20:28 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_ne >= 40
I agree!

2024-06-27 20:50 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    snowflake_warehouse = get_snowflake_refresh_warehouse(small="XL")
Let's default to XS/XL, and adjust as needed

2024-06-27 20:51 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_ne >= 40
I'm a little agnostic, if you and @kengodleskidot think this is an important part of the check, I'd be okay with it, we should just document it as an additional criteria

2024-06-27 22:23 UTC, mmmiah reviewed
Overall great work@ britt. I think that you still did not consider 5, five minutes windows to determine the bottleneck. I will be back to review again Once you have more update. I have gone through the code and left some clarification comments. Thank you for doing all these.

2024-06-27 22:23 UTC, mmmiah commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_ne >= 40
This tag of starting bottleneck will be helpful when you will have continuous bottleneck for several stations. In that case you need to have separate tracking column. I did some QA/QC on outputs. It looks great to me. but It will be great if you can add the starting tracking of bottleneck. For example if your binary bottleneck results like this 1,1,1,1,1,0,1,1,.., then your first 1 (station will be tracked as 1 and then 7th number station will be also 1. This will help to identify particular location where congestion start and do some more engineering investigations on how to improve the traffic conditions.
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/166866681/157efad2-ee20-40ff-bf6f-92d3717183f8)

2024-06-27 22:23 UTC, mmmiah commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +                and speed_prev_sw >= 40
The criteria can be dropped for bottleneck determination to make sure it is not impacting the determination of bottleneck, however, it can be useful to track which station is the beginning of bottleneck.

2024-06-28 19:55 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
sw = south / west and ne = north / east. it's to account for the direction of highway when the postmile is sorted in one way which in our case is ascending

2024-06-28 19:56 UTC, britt-allen commented
thanks for doing QA/QC, the model and columns have changed since you last reviewed if you want to take another look @mmmiah

2024-06-28 19:57 UTC, mmmiah commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
This makes sense

2024-06-28 20:07 UTC, britt-allen commented
These are current results of my QA/QC:

The green underlined data is highlighting the 5 instances of when the criteria is met out of a rolling window of 7

<img width="1689" alt="Screenshot 2024-06-28 at 1 04 50 PM" src="https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/47340362/ff132cd9-0006-48c3-b44c-f6ae670d6b0a">

2024-06-28 20:28 UTC, mmmiah approved these changes
Looks good to me!

2024-06-28 20:30 UTC, ian-r-rose commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +    snowflake_warehouse = get_snowflake_refresh_warehouse(small="XS")
Can you put `big="XL" here?

2024-06-28 20:30 UTC, ian-r-rose commented on transform/models/intermediate/performance/_performance.yml
> +        description: tk
Still TK?

2024-06-28 20:30 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as speed_prev_sw,
These two don't seem like they are actually used in any of the calculations. I think it should be safe to remove them.

2024-06-28 20:30 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as distance_delta_sw
Can you add a descriptive comment for future readers about how "upstream" and "downstream" is determined here? Something along the lines of:

> Absolute postmile increases going north and east. Therefore, when the direction of the freeway for a station is north or east, the "upstream" station has a smaller postmile, and we need to `lag` to get the speed there. When the direction is west or south, the "upstream" station has a larger postmile, and we need to `lead` to get the speed there.

@kengodleskidot does that description of how postmile works sound correct to you?

Based on what I wrote above, I think that the SW versions of the deltas might actually be reversed. Speed delta should always be the speed of the current station minus the speed of the upstream station. This might be able to be validated against a known bottleneck, if @kengodleskidot has any examples handy

2024-06-28 21:14 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as distance_delta_sw
Added, will make changes pending further review and feedback

2024-07-01 17:19 UTC, britt-allen commented
I excluded the following columns `exclude (latitude, longitude, bottleneck_check, bottleneck_check_summed)` so for anyone doing QA/QC you may want to temporarily add them back. QA/QC can also be done without them.

2024-07-01 17:20 UTC, britt-allen commented
Can I get final review and approval or feedback on this today so I can easily move on to other parts of the bottleneck problem? @ian-r-rose @kengodleskidot

2024-07-01 17:23 UTC, ian-r-rose commented
> Can I get final review and approval or feedback on this today so I can easily move on to other parts of the bottleneck problem? @ian-r-rose @kengodleskidot

I still think that my comment above might be something that needs correcting: a sign error in the speed delta computation will flag speed *increases* instead of *decreases* as bottlenecks. This is something that should be possible to check in QA for this PR.

2024-07-02 20:22 UTC, ian-r-rose approved these changes
Looks good to me, thanks @britt-allen!

2024-07-02 20:56 UTC, merged

2024-07-02 21:32 UTC, kengodleskidot requested changes
@britt-allen this is coming along well but a few comments we can talk about or you can address directly.

2024-07-02 21:32 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as speed_delta_sw,
The speed_delta_sw looks off. Below is an example of a speed increase between the upstream (316438 @ 8.01 mph) and downstream (318612 @28.75 mph) stations but the calculation results in a negative value (-20.73 mph) which I believe we are assuming is a speed reduction based on the logic on lines 86 and 92. Traffic is travelling Westbound on I-80.
STATION_AGG_FIVE_MINUTES Model:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/ea90fea0-757c-4ee7-93bb-4fdf58102c91)
Bottleneck Model:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/8e48225e-1098-4ada-8b6f-24a445f7fa02)

In the next example the speed_delta_ne looks ok. Below is an example of a speed increase between the upstream (3016071 @ 67.11 mph) and downstream (3001021 @ 67.35) stations and the calculation results in a positive value (0.25 mph) which I believe we are assuming is a speed increase based on the logic on lines 86 and 92. Traffic is travelling northbound on route 99.
STATION_AGG_FIVE_MINUTES Model:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/56ce9011-c430-4580-ac3f-64aee78bf818)
Bottleneck Model:
![image](https://github.com/cagov/caldata-mdsa-caltrans-pems/assets/124397677/c5cd0116-1495-4663-bfe0-1d3968143188)

@britt-allen let me know if you want to go over this.

2024-07-02 23:27 UTC, britt-allen commented on transform/models/intermediate/clearinghouse/int_clearinghouse__station_agg_five_minutes.sql
> +),
Let's discuss in our weekly session tomorrow @kengodleskidot

2024-07-02 23:34 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as distance_delta_sw
Based on what you posted in #260 and my latest correction the postmiles are being handled correctly.

2024-07-02 23:54 UTC, britt-allen commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as speed_delta_sw,
let's discuss this tomorrow in our modeling session, I am having trouble replicating

2024-07-02 23:54 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +),
The reason why the "Good" filter is done in the `int_clearinghouse__station_agg_five_minutes` model is that it aggregates data from the detector level to the station level (since bottlenecks don't really make sense at the lane level). We wanted to only include data we felt was reliable in the aggregation up to "station", so filtered the detectors for "Good" status. But since the status is only available at the detector level, it had to be done a bit earlier.

In the future, this model (and all the performance models) are intended to be based on imputed data, where there should be less need to filter for "Good", at least based on my understanding of the plan. So I think this model `int_clearinghouse__station_agg_five_minutes` would be considered a temporary model until the imputation is ready. Does that make sense?

2024-07-03 00:01 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as speed_delta_sw,
Thanks for the nice example @kengodleskidot, looking forward to digging in tomorrow! As my dissertation advisor used to say "you only need to make an even number of sign errors!"

2024-07-03 18:45 UTC, britt-allen commented on transform/models/intermediate/performance/_performance.yml
> +      conditions - 1) There is a drop in speed of at least 20 mph between stations, not time. 2) The speed
Good catch!

2024-07-03 21:25 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +),
Thank you for the explanation and it makes sense to me.

2024-07-03 21:27 UTC, kengodleskidot commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as speed_delta_sw,
I reviewed the same data points using the updated code (post merge) and the signs look good for speed_delta_sw values.

2024-07-03 21:29 UTC, ian-r-rose commented on transform/models/intermediate/performance/int_performance__bottlenecks.sql
> +            as speed_delta_sw,
woo hoo!