Review of virtual environments
cagov/caldata-mdsa-caltrans-pems pull request #463
Opened 2024-11-05 23:21 UTC by YanlinQi-BIA

Both poetry-based virtual environments for the Oracle Puller and AWS Uploader have been configured. The PR is set up for review.
Oracle Puller: /data/projects/crawler/poetry.lock

2024-11-06 16:47 UTC, pingpingxiu-DOT-ca-gov requested changes
Please see my review inline. 

The priority is to setup the PR right so that only up to 4 files are shown to be changed.

2024-11-06 16:47 UTC, pingpingxiu-DOT-ca-gov commented on pyproject.toml
Hi @YanlinQi-BIA , it will be another big milestone to get code into PR process, after you've made the current milestone of integrating poetry on the production env. 

There are steps that needs to be done from the current stage: 
1. Make sure you are checking out from the latest main branch, rather than an old historical version. Currently, main has another 69 commits that occurred after you've made your branch, so the PR is showing a lot of Files changed (30). If you configured the PR right, then you only need to change 2 (poetry.lock, pyproject.toml) or 4 files (for oracle puller, and for uploader, having their own peotry.lock, pyproject.toml. 

2. Please have a walkthrough on the description guiding reviewer about the task's background, and which file to look first, which is after, so the reviewer have a mental picture what they are expected on the review task. 

3. The folder we are working on is strictly under the `jobs/data_relay` folder. You can create subfolders if needed.

2024-11-07 16:36 UTC, YanlinQi-BIA commented on pyproject.toml
Sure @pingpingxiu-DOT-ca-gov, I'll confirm the correct steps for submitting the PR with you and make the necessary fixes today.

2024-11-07 22:45 UTC, YanlinQi-BIA commented
**Follow-up Discussion with Pingping:**

1. **Reason for PR Not Showing:**
    
    The sub-branch `YanlinQi-BIA-patch-1` was already merged into the `main` branch after completing `data_relay.md`. As a result, the PR does not appear because the sub-branch is now part of `main`.
    
2. **Solution:**
    - Created a new branch, `make-use-of-virtual-env`, and submitted a new PR from this branch.
    - Will close the previous PR to avoid any redundancy.

2024-11-08 00:13 UTC, closed without merging