Create plotly_eda_dashboard.py
cagov/caldata-mdsa-caltrans-pems pull request #50
Opened 2024-01-30 00:14 UTC by mmarks13

Initial commit. To use dashboard, just run this file. This will start a local server at http://127.0.0.1:8050/

2024-01-30 01:42 UTC, mbobra requested changes
@mmarks13 Thank you for this submission.

* I see the code imports packages like `plotly` and `dash`, which aren't included in `pyproject.toml`. Consider including an updated environment and lock file with this submission. 
* Consider adding documentation following [these guidelines](https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/main/docs/writing-documentation.md) about the technical design and output of this code (as well as how to run it). 
* Consider adding docstrings to the functions ([Google Python Style Guide 3.8.1](https://google.github.io/styleguide/pyguide.html#s3.8.1-comments-in-doc-strings)) that include type annotation (see the [mypy type hints cheat sheet](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)).
* Consider linting this code using the pre-commit hooks (see guidelines in the [CalData Data Services and Engineering Infrastructure](https://cagov.github.io/data-infrastructure/code-review/#use-linters-and-formatters) documentation).

2024-01-30 15:09 UTC, ian-r-rose reviewed
Cool stuff!

2024-01-30 15:09 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +    aggregated_df_filtered.set_index('ID',inplace = True)
You reset the ID index, then set it back to ID again here, which is a lot of extra work in a callback. I wonder if there is some performance to be gained by not doing this

2024-01-30 15:09 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +    aggregated_df_filtered[agg_col] = aggregated_df_filtered[agg_col].astype('float32').round(2).astype('float16')
Rather than rounding and doing lots of type conversion (which may be expensive inside of a callback), can we just use the values directly? If the rounding is for display, I would hope that dash has some formatting options so one doesn't have to do all this math.

2024-01-30 15:09 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +    )
Did you see a performance difference between these two? The former is more idiomatic pandas

2024-01-30 15:09 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +    result = ibis_con.sql(sql_str).execute()
It looks like you're mostly not using the query building functionality of ibis. In that case, it might be simpler to just use a raw snowflake connector.

2024-01-30 15:46 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    return math.ceil(num * 10) / 10
Good catch. I was using these in earlier version.

2024-01-30 15:48 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +int16_colnames = ['FLOW_1_COUNT','FLOW_2_COUNT', 'FLOW_3_COUNT', 'FLOW_4_COUNT','OCCUPANCY_1_COUNT', 'SPEED_1_COUNT']
My first version had just flow_1, occupancy_1, and speed_1. I just wanted to see some data from the other lanes and didn't want to scale up too fast.

2024-01-30 16:03 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +expected_num_daily_observations = 2440
I'm assuming you're talking about the TBL_STATION_DAY_AGG_STATS_V2 table? I made this table in snowflake. How do you all do version control on queries?

2024-01-30 16:04 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    aggregated_df_filtered.set_index('ID',inplace = True)
good catch. Indexing is about as expensive as it gets.

2024-01-30 16:07 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +                   , 'marginLeft': '10px','marginRight': '10px','marginTop': '0px','marginBottom': '0px'}
Definitely. I admittedly didn't do much reading of the documentation on the formatting part, so I might have been missing something. I originally had things like 'margin-right', 'margin-left', etc. and it didn't appear to be working.

2024-01-30 16:10 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    aggregated_df_filtered[agg_col] = aggregated_df_filtered[agg_col].astype('float32').round(2).astype('float16')
yeah. This was a painful hack just to get things moving along. There was some bug or unknown issue with how the `float16` values were being processed downstream.

2024-01-30 16:10 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +expected_num_daily_observations = 2440
No, I'm referring to `2440`. What does this number come from? Can it be pushed to Snowflake?

2024-01-30 16:11 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +expected_num_daily_observations = 2440
We use dbt to manage version controlled queries in Snowflake

2024-01-30 16:11 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    )
I didn't test it outright, but from what I read, using `query` is more efficient.

2024-01-30 16:12 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    database="RAW_DEV/CLEARINGHOUSE"
Good to know. Thanks

2024-01-30 16:12 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +    )
I'd be curious to see a reference, I often see `query` from dplyr users, but rarely from pandas devs.

2024-01-30 16:16 UTC, ian-r-rose commented on pems/plotly_eda_dashboard.py
> +    result = ibis_con.sql(sql_str).execute()
I'm curious as well! I'll bet the performance of the queries is almost identical, but there may be differences in the deserialization logic. On the one hand, Snowflake, as the first-party connector, may do clever things in sending the data over the wire and materializing as a pandas dataframe. On the other hand, ibis is developed by the arrow core team, so they might also have some tricks up their sleeves that the Snowflake folks don't. I could see it cutting both ways.

2024-01-30 16:43 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    )
It looks like you may be right to question this. These were some of the articles I came across:
https://www.askpython.com/python-modules/pandas/query-pandas-dataframe
https://stackoverflow.com/questions/67341369/pandas-why-query-instead-of-bracket-operator

This one appears show the opposite though:
https://stackoverflow.com/questions/49936557/pandas-dataframe-loc-vs-query-performance

2024-01-30 16:48 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +expected_num_daily_observations = 2440
Again, good catch. That number should be 2880 and it is the number of 30 second periods in a day. 

I didn't really end up using this too much, so it didn't get much scrutiny. 

It could be pushed to snowflake, but this operation wasn't actually done locally after I saved the .pkl file the first time. After that, I just loaded that table from local disk each time.

2024-01-30 17:08 UTC, mmarks13 commented on pems/plotly_eda_dashboard.py
> +    aggregated_df_filtered.set_index('ID',inplace = True)
Well, changing this broke my code. Given this is a POC, I'm going to leave it alone for now.

2024-01-30 17:34 UTC, mmarks13 commented
Thanks @mbobra. 
> * I see the code imports packages like `plotly` and `dash`, which aren't included in `pyproject.toml`. Consider including an updated environment and lock file with this submission.
This should be fixed in the latest commit. 


> * Consider adding documentation following [these guidelines](https://github.com/cagov/caldata-mdsa-caltrans-pems/blob/main/docs/writing-documentation.md) about the technical design and output of this code (as well as how to run it).
> * Consider adding docstrings to the functions ([Google Python Style Guide 3.8.1](https://google.github.io/styleguide/pyguide.html#s3.8.1-comments-in-doc-strings)) that include type annotation (see the [mypy type hints cheat sheet](https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)).
> * Consider linting this code using the pre-commit hooks (see guidelines in the [CalData Data Services and Engineering Infrastructure](https://cagov.github.io/data-infrastructure/code-review/#use-linters-and-formatters) documentation).

Thank you for sharing these resources. These practices are ideal for ensuring code quality, particularly in a production environment. However, there are trade-offs in terms of time and resources that I think we need to consider. This is a conversation that merits broader AAE team engagement to determine when the investment in comprehensive documentation and strict code standards justifies the costs, and when it's more strategic to accept some 'technical debt' as a part of agile development. It's all about finding the right balance for our project goals.

2024-01-30 17:56 UTC, ian-r-rose commented
> Thank you for sharing these resources. These practices are ideal for ensuring code quality, particularly in a production environment. However, there are trade-offs in terms of time and resources that I think we need to consider. This is a conversation that merits broader AAE team engagement to determine when the investment in comprehensive documentation and strict code standards justifies the costs, and when it's more strategic to accept some 'technical debt' as a part of agile development. It's all about finding the right balance for our project goals.

These practices are also important for establishing standards for legibility and house style within larger projects. When used as pre-commit hooks, they are fairly straightforward to apply as part of a normal workflow. This project has multiple stakeholders with many different backgrounds, and without having some code standards things tend to get out of control quite quickly. For this reason, we've enabled a rule to block merging until CI checks pass.

We at CalData are supposed to be modeling good practices, and I do not think that basic CI gets in the way of agile development, nor does it take unnecessary time or resources.

2024-01-30 18:16 UTC, mmarks13 commented
> These practices are also important for establishing standards for legibility and house style within larger projects. When used as pre-commit hooks, they are fairly straightforward to apply as part of a normal workflow. This project has multiple stakeholders with many different backgrounds, and without having some code standards things tend to get out of control quite quickly. For this reason, we've enabled a rule to block merging until CI checks pass.
> 
> We at CalData are supposed to be modeling good practices, and I do not think that basic CI gets in the way of agile development, nor does it take unnecessary time or resources.


All good points @ian-r-rose. This is exactly the conversation I think we need to have with the larger AAE team. For now, I will ask Kim how she would like me to prioritize my work.

2024-02-10 01:24 UTC, mbobra approved these changes
@mmarks13 I pushed a new commit to your branch with reformatted docstrings (see [this example in the Google Python Style Guide](https://google.github.io/styleguide/pyguide.html#383-functions-and-methods)) and all the pre-commit checks passed, huzzah! I'm approving this PR. You can merge right now if you wish. Or you can address some (or all) of @ian-r-rose's comments (or not, up to you).

2024-02-12 17:20 UTC, merged

2024-02-12 17:21 UTC, mmarks13 commented
Thanks @mbobra!